name: cell2mol
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=21.4.0
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - certifi=2021.10.8
  - cycler=0.11.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.28.5
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.2
  - icu=69.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libffi=3.4.2
  - libglib=2.70.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.2
  - networkx=2.6.3
  - numexpr=2.8.0
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.0.0
  - packaging=21.3
  - pandas=1.3.5
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.3.1
  - pixman=0.40.0
  - pluggy=1.0.0
  - py=1.10.0
  - pycairo=1.20.1
  - pycifrw==4.4.3
  - pyparsing=3.0.6
  - pytest=6.2.5
  - python=3.9.9
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - rdkit=2021.09.3
  - readline=8.1
  - reportlab=3.5.68
  - scipy=1.7.3
  - setuptools=60.5.0
  - six=1.16.0
  - sqlalchemy=1.4.29
  - sqlite=3.37.0
  - tbb=2021.5.0
  - tk=8.6.11
  - toml=0.10.2
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.1
